### ISSUE TITLE
introduction section too long

### ISSUE THREAD

**Issue by myf** [SEL-Columbia/bamboo-meteor-client#22]
currently it display every single column of a dataset. When the dataset is 73 columns long it is not fun to look through. we would have to integrate them in one scrollable frame and make it a little more humane to read.

**Comment by nanzhuwang** [comment]
I try to show the first 5 entries with a "more" button if there are more than 5 entries. After clicking the "more", all entries display and a "hide" button appears. After clicking the "hide", it goes back to the first 5 entries with the "more" button.

Also, we could implement scroll bar instead of that. The only concern is that we already have a select box "view" whose function is like scroll bar.
