### ISSUE TITLE
move the waiting icon in the graph area

### ISSUE THREAD

**Issue by nanzhuwang** [SEL-Columbia/bamboo-meteor-client#68]
it makes sense

**Comment by myf** [comment]
tried. but it was unsuccessful since meteor is reactive and this waiting icon if statement cannot be in any meteor.ui.render generated blocks. if anyone has a better suggestion please let me know. right now it is in the control graph panel. in the near future we would change to front-end logic to make it more user friendly. for now it's too much to do just for this one icon.
